version: 2
jobs:
  test:
    docker:
      - image: golang:1.11.5
    working_directory: /go/src/github.com/jdrouet/marionette
    steps:
      - run: go get -u github.com/golang/dep/cmd/dep
      - checkout
      - run: make vendor
      - run: make test

  build:
    docker:
      - image: golang:1.11.5
    working_directory: /go/src/github.com/jdrouet/marionette

    steps:
      - run: go get -u github.com/golang/dep/cmd/dep
      - checkout
      - run: make vendor
      - run: make build
  
  e2e:
    docker:
      - image: ubuntu:latest
    working_directory: ~/marionette-test
    steps:
      - run: git clone git@github.com:jdrouet/marionette-test.git ~/marionette-test
      - run: git checkout rebuild-client-only

workflows:
  version: 2
  normal:
    jobs:
      - test
      - build
      - e2e:
          requires:
            - build
